services:
  webapp:
    container_name: obscreen
    restart: unless-stopped
    image: jierka/obscreen:latest
    environment:
    - DEBUG=false
    - REVERSE_PROXY_MODE=false
    - PORT=5000
    volumes:
      - .:/app
      - ${LX_FILE-./var/run/dummy}:/app/var/run/lxfile
    ports:
      - "${PORT}:5000"
