version: '3.7'
services:
  webapp:
    container_name: obscreen
    restart: unless-stopped
    image: jierka/obscreen:latest
    environment:
    - DEBUG=false
    - REVERSE_PROXY_MODE=false
    - LX_FILE=/app/var/run/lxfile
    volumes:
      - .:/app
      - /home/pi/.config/lxsession/LXDE-pi/autostart:/app/var/run/lxfile
