services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obscreen
    restart: unless-stopped
    image: obscreen:latest
    environment:
      - DEBUG=${DEBUG-false}
      - PORT=${PORT-5000}
      - SECRET_KEY=${SECRET_KEY-ANY_SECRET_KEY_HERE}
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}