services:
  webapp:
    container_name: obscreen
    restart: unless-stopped
    image: jierka/obscreen:latest
    environment:
      - DEBUG=false
      - PORT=5000
      - SECRET_KEY=ANY_SECRET_KEY_HERE
    volumes:
      - ./data/db:/app/data/db
      - ./data/uploads:/app/data/uploads
    ports:
      - 5000:5000
