services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obscreen
    restart: unless-stopped
    image: obscreen:latest
    environment:
      - DEBUG=${DEBUG-false}
      - PORT=${PORT-5000}
      - PLAYER_AUTOSTART_FILE=/app/var/run/play
      - SECRET_KEY=${SECRET_KEY-ANY_SECRET_KEY_HERE}
    volumes:
      - .:/app
      - ${PLAYER_AUTOSTART_FILE-/dev/null}:/app/var/run/play
    ports:
      - ${PORT}:${PORT}